# Generated by Django 2.0.5 on 2018-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api4', '0004_auto_20181126_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], default=0, verbose_name='性别'),
        ),
    ]
