# Generated by Django 2.0.5 on 2018-12-05 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api4', '0005_auto_20181203_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpick',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pick_relate_product', to='product.Product', verbose_name='产品'),
        ),
    ]
