# Generated by Django 2.0.5 on 2018-12-05 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_external_name'),
        ('api4', '0006_auto_20181205_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpick',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pick_relate_product', to='product.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='productpick',
            name='product_code',
            field=models.CharField(blank=True, max_length=132, null=True, verbose_name='产品标识'),
        ),
    ]
